services:
  db-oficina:
    image: postgres:16
    container_name: postgres_oficina
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: c2VuaGE
      POSTGRES_DB: oficina_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: